---
elastic_stack_version: "8.19.14"
kibana_deb_url: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-{{ elastic_stack_version }}-amd64.deb"
kibana_deb_path: "/tmp/kibana-{{ elastic_stack_version }}-amd64.deb"
